### ISSUE TITLE
Question - What theme is shown in the preview?

### ISSUE THREAD

**Issue by buttertone** [niksingh710/minimal-tmux-status#1]
Hello. Thanks for sharing the project. What theme are you using for your terminal in the preview?

**Comment by niksingh710** [comment]
> Hello. Thanks for sharing the project. What theme are you using for your terminal in the preview?

There is no colorscheme in the preview it is just pywal extracting colors from my wallpaper that m using on terminal.

**Comment by niksingh710** [comment]
I guess I have already answered your question, so closing the issue.
