### ISSUE TITLE
0 on the right side of status bar.

### ISSUE THREAD

**Issue by Redoxahmii** [niksingh710/minimal-tmux-status#10]
![image](https://github.com/niksingh710/minimal-tmux-status/assets/13983258/4a9aa6c5-4d7f-442f-8834-6670eabcc5ca)

Is there some way to get rid of that 0 that shows by default on the right side?

**Comment by Redoxahmii** [comment]
Just figured out that it is takes the name of the session. Is there some option to disable that?

**Comment by niksingh710** [comment]
> Just figured out that it is takes the name of the session. Is there some option to disable that?

Can you please share your config? As I don't get `number` for session in the default configuration.

**Comment by niksingh710** [comment]
If you want to disable it completly.
Then `set -g @minimal-tmux-right false` this should do that.
And if you want to remove the numbers then ig you should use `set -g @minimal-tmux-status-right ""`

**Comment by Redoxahmii** [comment]
I wanted to keep some text of my own but not show the session name there but i think that is not the functionality of it here as using this removes all the text and does not show anything else then. Still thanks for the quick info.

**Comment by niksingh710** [comment]
> I wanted to keep some text of my own but not show the session name there but i think that is not the functionality of it here as using this removes all the text and does not show anything else then. Still thanks for the quick info.

What you want ig can be easily achieved by this snippet 
```
set -g @minimal-tmux-status-right " "
set -g @minimal-tmux-status-right-extra "<text you want>"
```

**Comment by Redoxahmii** [comment]
> > I wanted to keep some text of my own but not show the session name there but i think that is not the functionality of it here as using this removes all the text and does not show anything else then. Still thanks for the quick info.
> 
> What you want ig can be easily achieved by this snippet
> 
> ```
> set -g @minimal-tmux-status-right " "
> set -g @minimal-tmux-status-right-extra "<text you want>"
> ```
> 
> make sure to remove `set -g @minimal-tmux-right false` and `tmux kill-server` and then check in tmux

What i was missing was the blank space in the option `@minimal-tmux-status-right` thanks for the info!
