### ISSUE TITLE
refer to code on the status line

### ISSUE THREAD

**Issue by Eloquencere** [niksingh710/minimal-tmux-status#13]
- What is supposed to be the value to configure to view tmux leader key enabled state on the bottom left? In the configuration it says "refer to code" 
- the current directory isn't being displayed it's been replaced with '0' and in the configuration the left half of the screen has been specified with '#S'

**Comment by Eloquencere** [comment]
It shows the leader key state by default now so, there's nothing to configure. 
The second point was just a misunderstanding on my part, I was very new to tmux, and the number 0 was the default session number assigned by tmux so there was nothing wrong with the plugin

**Comment by WellingtonFonseca** [comment]
> It shows the leader key state by default now so, there's nothing to configure. The second point was just a misunderstanding on my part, I was very new to tmux, and the number 0 was the default session number assigned by tmux so there was nothing wrong with the plugin

I have this 'refer to code' problem and tmux doesn't appear as I activate the prefix, how did you fix it? I'm new to tmux

**Comment by parnavh** [comment]
> I have this 'refer to code' problem and tmux doesn't appear as I activate the prefix, how did you fix it? I'm new to tmux

@WellingtonFonseca `refer to code` is not a value, it tells you to refer the [line](https://github.com/niksingh710/minimal-tmux-status/blob/d7188c1aeb1c7dd03230982445b7360f5e230131/minimal.tmux#L62) for the default value since it is too complicated for showing in the showcase:
```status_left=$("$left_state" && get_tmux_option "@minimal-tmux-status-left" "${default_color}#{?client_prefix,,${indicator}}#[bg=${bg},fg=${fg},bold]#{?client_prefix,${indicator},}${default_color}")```
