### ISSUE TITLE
Expanded screen icon outside the colored area in the current tab

### ISSUE THREAD

**Issue by brnsantos7** [niksingh710/minimal-tmux-status#16]
When I installed the plugin, I noticed that the full-screen icon is now located outside the colored area of the current tab. If I'm not mistaken, in previous updates, the icon was positioned inside this area. Was this change intentional? I did not modify any configuration file settings; I simply installed the plugin.
![Screenshot 2024-10-19 at 01 28 55](https://github.com/user-attachments/assets/acce1d21-20da-4251-a54b-e3ed1bbaafb8)

**Comment by niksingh710** [comment]
Just fixed this, This was introduced in a latest pr #15, please check and confirm.
