### ISSUE TITLE
Newer nerd fonts have removed the maximized window icon

### ISSUE THREAD

**Issue by vaaleyard** [niksingh710/minimal-tmux-status#4]
It looks like newer nerd fonts have removed the icon used by this theme when there's a maximized window: https://github.com/niksingh710/minimal-tmux-status/blob/5dbcb1a1e56cf41d13a81d127cb40034755d10ad/theme/minimal-status.tmux#L7

I just downloaded jetbrains font and it's not shown... Is it a good idea to change it?

I've searched in their icons and couldn't find a better one, tough. But, I've sticked with the _eb81_.

**Comment by niksingh710** [comment]
On the [cheat sheet](https://www.nerdfonts.com/cheat-sheet) search for the term `nf-md-fullscreen`

As for me, it shows like this
![image](https://github.com/niksingh710/minimal-tmux-status/assets/60490474/f6f7aacd-5fda-4461-8e56-6748730fd968)

Check if the one that is not removed rendering correctly?
maybe it is possible that the one i have included is removed.
