### ISSUE TITLE
How to move window labels to left?

### ISSUE THREAD

**Issue by SameerJadav** [niksingh710/minimal-tmux-status#6]
Great work with this plugin. Absolutely love it.

I just want to move the window labels to the left and remove that `tmux` indication. How can I do that?

![image](https://github.com/niksingh710/minimal-tmux-status/assets/109742866/6edbf269-7ed2-498e-b730-00823e877650)

**Comment by niksingh710** [comment]
> Great work with this plugin. Absolutely love it.
> 
> I just want to move the window labels to the left and remove that `tmux` indication. How can I do that?
> 
> ![image](https://private-user-images.githubusercontent.com/109742866/292735084-6edbf269-7ed2-498e-b730-00823e877650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODQ1MTcsIm5iZiI6MTcwMzU4NDIxNywicGF0aCI6Ii8xMDk3NDI4NjYvMjkyNzM1MDg0LTZlZGJmMjY5LTdlZDItNDk4ZS1iNzMwLTAwODIzZTg3NzY1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwOTUwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzhmMzRmM2UxNWM3ZWFhYWI5NGE4Mzc2ZjAyODRiZjlkZjMxMjI4MTgyNjNmMjFmZDBhNWY5MGVkMzI3MzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8eU7r6pUIrIgPjLsvkkyonA5ORCB6UZmOm2da9BVmIg)

in commit 5acbc42 i introduced a few variables to control stuff.

to achieve what you want, you can do
```
set -g @minimal-tmux-bg "#698DDA"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator-str ""
```

Make sure to update the plugin `prefix+U`

**Comment by SameerJadav** [comment]
Thank you so much!

**Comment by niksingh710** [comment]
> Thank you so much!

sorry but i was fiddling to make sure that if no override given then the default value should be used.

now to acheive what you want you may need these variables instead of above.

```
set -g @minimal-tmux-indicator false
set -g @minimal-tmux-justify "left"
```

**Comment by niksingh710** [comment]
Confirm me if using the new one get's you as expected result so i will be closing the issue.
