### ISSUE TITLE
[Bug Report] reload required to apply customization

### ISSUE THREAD

**Issue by yqlbu** [niksingh710/minimal-tmux-status#8]
## Summary

Hi, thanks for introducing this minimum status bar implementation, which is exactly what I have been looking for.

However, I would like to report some issue I met while adopting it. See below details.

## Config

```conf
# Tmux Status Bar
set -g @minimal-tmux-bg "#c2dcf2"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator-str "   "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "bottom"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

# To add or remove extra text in status bar
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""

# Not recommended to change these values
set -g @minimal-tmux-status-right "#S"
set -g @minimal-tmux-status-left ""

# If getting strings cut in left status or right 
# Here 20 is the length of the characters in the string
set -g status-left-length 20
```

## Expected Behaviour

I expect that my customization should be able to apply without the need to reload at tmux startup.

![image](https://github.com/niksingh710/minimal-tmux-status/assets/31861128/0856b210-7e5f-443d-85d1-1cd2f442e336)

## Actual Behaviour

However, `tmux reload` is required in order to apply customization.

> [!NOTE]
> Screenshot demonstrates the initial status at tmux startup:

![image](https://github.com/niksingh710/minimal-tmux-status/assets/31861128/2d97d691-c810-49e5-a220-5b50e098dedc)

**Comment by niksingh710** [comment]
There is no need to put all the variables, as their default values will be used.

Please try `tmux kill-server` and then test this if it requires reloading of tmux.

**Comment by yqlbu** [comment]
I tried your suggestion to remove redundant configs in `$HOME/.tmux.conf`. However, the reload issue still persists. I will keep you updated once I find the root cause.

**Comment by niksingh710** [comment]
> I tried your suggestion to remove redundant configs in `$HOME/.tmux.conf`. However, the reload issue still persists. I will keep you updated once I find the root cause.

Have you tried `tmux kill-server` once? As for me, it happened. But once I killed all tmux server and started tmux again, everything is working fine.

**Comment by yqlbu** [comment]
> > I tried your suggestion to remove redundant configs in `$HOME/.tmux.conf`. However, the reload issue still persists. I will keep you updated once I find the root cause.
> 
> Have you tried `tmux kill-server` once? As for me, it happened. But once I killed all tmux server and started tmux again, everything is working fine.

I found out the root cause: the reason why my config is not loaded is due to not sourcing `tpm.conf` in the end of `$HOME/.tmux.conf`

```conf
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

After putting the above line to the bottom of `.tmux.conf`, I manage to get the customization applied at tmux startup.

Thanks for your kind help!

**Comment by yqlbu** [comment]
Resolved.
