### ISSUE TITLE
Option to always show the expanded icon

### ISSUE THREAD

**Issue by DovieW** [niksingh710/minimal-tmux-status#9]
Currently the expanded icon only shows on the active tab. 
Would it be possible to add an option to always show the icon?

**Comment by DovieW** [comment]
This works but there's an extra space when the tab is not active

```bash
show_expanded_icon_for_all_tabs=$(get_tmux_option "@minimal-tmux-show-expanded-icon-for-all-tabs" false)
tmux set-option -g window-status-current-format "#[bg=${bg},fg=#000000] #I:#W${expanded_icon}"
expanded_icon="#{?window_zoomed_flag, 󰊓 , }"

if [ "$show_expanded_icon_for_all_tabs" = true ]; then
    tmux set-option -g window-status-format "${window_status_format}${expanded_icon}"
else
    tmux set-option -g window-status-format "${window_status_format}"
fi
```

**Comment by niksingh710** [comment]
ig the last commit should fix it.



> This works but there's an extra space when the tab is not active
> 
> ```shell
> show_expanded_icon_for_all_tabs=$(get_tmux_option "@minimal-tmux-show-expanded-icon-for-all-tabs" false)
> tmux set-option -g window-status-current-format "#[bg=${bg},fg=#000000] #I:#W${expanded_icon}"
> expanded_icon="#{?window_zoomed_flag, 󰊓 , }"
> 
> if [ "$show_expanded_icon_for_all_tabs" = true ]; then
>     tmux set-option -g window-status-format "${window_status_format}${expanded_icon}"
> else
>     tmux set-option -g window-status-format "${window_status_format}"
> fi
> ```

yep, this works and implemented while referencing this.
Just wasn't able to get the part where you were mentioning space.

**Comment by DovieW** [comment]
With your change, the spacing is consistent for both active and non-active tabs, but there is an additional space on each side of the name for all tabs. I don't mind it

Before this change:
![image](https://github.com/niksingh710/minimal-tmux-status/assets/32934685/9163dbac-a404-4104-ac94-410ed7b105bc)

After:
![image](https://github.com/niksingh710/minimal-tmux-status/assets/32934685/c99b1ce7-8dd1-467f-a5c6-d82d95aefb84)

**Comment by niksingh710** [comment]
Yeah, the space is introduced by tmux ig.
If this works for you, then please close the issue.
